version: '3'
services:
  db:
    image: postgres:alpine
    environment:
     - POSTGRES_USER=rails
     - POSTGRES_PASSWORD=web
     - POSTGRES_DB=web_development
  web:
    build: ./web
    environment:
     - WEB_DATABASE_USERNAME=rails
     - WEB_DATABASE_PASSWORD=web
     - WEB_DATABASE_DB=web_development
     - WEB_DATABASE_HOST=db
     - WEB_DATABASE_PORT=5432
    # command:   bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
