# Shared secrets are available across all environments.
# shared:
#   api_key: a1B2c3D4e5F6
# Environmental secrets are only available for that specific environment.
development:
  secret_key_base: 85e458c985b28239b5184d1c1bb8feb324e339ce98ef9133d85d93be0f801283b7dc2232d0f1f573befb51e4b32f97b97eba6e9db5ca27d02c47c3436a61472c
test:
  secret_key_base: 9ec1d7288545de2e42dcb8dc516af08a28039436b607f7c1ad0faa92820fa03a5ab405c167b4ccd672c1dcb7e630af58058dc0878f80f1cf5045fbc964b9e7ff
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
